services:
  ai_agents:
    build:
      context: ./ai_agents
    ports:
      - "6000:6000"
    environment:
      - FLASK_APP=app.py
      - FLASK_RUN_PORT=6000
      - ACTIVE_PROVIDER_TYPE=groq
    secrets:
      - GROQ_API_KEY

  backend:
    build:
      context: ./backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0  # Ensure FLASK_RUN_HOST is set if using 'flask run' command
      - FLASK_RUN_PORT=5000
    
  json_db:
    build:
      context: ./json_db
    restart: unless-stopped
    ports:
      - "7000:7000"
    environment:
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0  # Ensure FLASK_RUN_HOST is set if using 'flask run' command
      - FLASK_RUN_PORT=7000
    

  
  frontend:
    build:
      context: ./frontend
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./frontend/src:/app/src
    environment:
      - VITE_APP_BACKEND_URL=http://localhost:5000
    depends_on:
      - backend

  ollama:
    image: ollama/ollama:latest
    ports:
      - 11434:11434
    volumes:
      - .:/code
      - ./ollama/ollama:/root/.ollama
    container_name: ollama
    pull_policy: always
    tty: true
    restart: always
    environment:
      - OLLAMA_KEEP_ALIVE=24h
      - OLLAMA_HOST=0.0.0.0

  
secrets:
  GROQ_API_KEY:
    file: GROQ_API_KEY.txt

volumes:
  json_db_data:
  json_db_files:
